# This is a simple yaml file for a simple web app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-apps
  labels:
    app: go-web-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-apps
  template:
    metadata:
      labels:
        app: go-web-apps
    spec:
      containers:
      - name: go-web-apps
        image: princeayiku/go-web-apps:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
