apiVersion: v1
kind: Service
metadata:
  name: go-web-apps
  labels:
    app: go-web-apps
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-web-apps
  type: ClusterIP
